### ISSUE TITLE
Images not Displaying in Documentation

### ISSUE THREAD

**Issue by SwindleA** [oss-slu/Pi4Micronaut#104]
Images are not included properly from the repository in the [documentation](https://oss-slu.github.io/Pi4Micronaut/#_rotary_encoder). 

![image](https://github.com/oss-slu/Pi4Micronaut/assets/60612512/9a02fe97-cbe3-4a5c-974e-38cb23e06365)

For some reason the path to the image is: `https://oss-slu.github.io/img/rotary_encoder_circuit.png` instead of `https://github.com/oss-slu/Pi4Micronaut/tree/main/micronautpi4j-utils/src/docs/asciidoc/img`. 

Possible solution may be setting the image directory: https://docs.asciidoctor.org/asciidoc/latest/macros/images-directory/

**Comment by ruthvikm** [comment]
Issue Fixed with pull request #110
