### ISSUE TITLE
Need to fix LCD1602 Helper 

### ISSUE THREAD

**Issue by ruthvikm** [oss-slu/Pi4Micronaut#116]
writeText and writeTextAtLine functions are not working as expected.

- [x] Use @Post instead of @Get in the LCD controller for writeText and writeTextAtLine functions
- [x] i2cconfig parameter was not used in the LCD Helper class. This gets the LCD config from application.yml file
- [x] Need function to turn on/off the LCD
- [ ] There are few other functionalities that are not implemented. For example, setting the cursor at particular position, blinking the cursor, displaying text at the middle of line, turning backlight on/off. Basically, use appropriate functions available in the components.jar to create functionalities in our helper class.
- [x] Make a note in the documentation under LCD section, says LCD works only with 32bit OS versions
- [ ] Add some comments in the controller class

**Comment by ruthvikm** [comment]
Use @Post to make it work instead of @Get

**Comment by SwindleA** [comment]
@post versus @get is not the issue. The LCD was working on my version of the OS, but when I try anyone else's version of Pi OS, the LCD does not work. I wiped my OS and tried to replicate how I configured the system and now the LCD does not work for me now. I think at one point I was messing with the paths for the libraries but I do not remember what I did or if that is the actual fix.  

Below is the image of the error. I tried different parameters for the LcdDisplay in the helper. I also made sure to pass the correct number of rows to the LcdDisplay. 

![image](https://github.com/oss-slu/Pi4Micronaut/assets/60612512/9d91cb68-d55e-4191-adfa-30cfba693d57)

**Comment by SwindleA** [comment]
> @post versus @get is not the issue. The LCD was working on my version of the OS, but when I try anyone else's version of Pi OS, the LCD does not work. I wiped my OS and tried to replicate how I configured the system and now the LCD does not work for me now. I think at one point I was messing with the paths for the libraries but I do not remember what I did or if that is the actual fix.
> 
> Below is the image of the error. I tried different parameters for the LcdDisplay in the helper. I also made sure to pass the correct number of rows to the LcdDisplay.
> 
> ![image](https://private-user-images.githubusercontent.com/60612512/305729983-9d91cb68-d55e-4191-adfa-30cfba693d57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjAzMDQsIm5iZiI6MTcwOTkyMDAwNCwicGF0aCI6Ii82MDYxMjUxMi8zMDU3Mjk5ODMtOWQ5MWNiNjgtZDU1ZS00MTkxLWFkZmEtMzBjZmJhNjkzZDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE3NDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMmJmMTEyZjA2YzQyNjlmZWUxYjU5M2M4NzJkN2UwZmY1ZGI2ZDFhYjhjMzE1MWI3Yzg4OTJlNTVmYzRiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usnc0JeDgFtuvmZjp6KR_OJWxh65p1UeSkMKy7zntLk)

This was solved by using the 32 bit version the Raspberry Pi Operating System.

**Comment by ruthvikm** [comment]
Most of the required functionalities are working
