### ISSUE TITLE
Need to fix the Dependency Injection for all the components

### ISSUE THREAD

**Issue by ruthvikm** [oss-slu/Pi4Micronaut#132]
Annotation "@ Named" was implemented in Controller classes instead of Helpers. Need to modify the Helper classes.

Annotation "@ Singleton" was not used in Helper classes to tell the DI container that only a single instance of the class should be created and shared. This instance is reused wherever that particular class is injected or called upon in the application.

**Comment by joefol** [comment]
Closing this issue because the DI changes are not needed. We are keeping the "@Named" in the controllers and "@Singleton" is not needed for components outside of Pi4J Factory.
