### ISSUE TITLE
Need config workflow diagram in documentation

### ISSUE THREAD

**Issue by ruthvikm** [oss-slu/Pi4Micronaut#210]
- [x] 6.1. Communicating with a Hardware Component - In this section we need a workflow diagram that shows the relation between Application.yml -> Controller -> Helper -> Creating context -> Raspberry Pi GPIO
- [x] Explanation required for the use of @Named - to fetch the configuration values from yml file.
- [x] Why it is important to follow the snake structure in yml file

**Comment by joefol** [comment]
Closed by PR #219
