### ISSUE TITLE
Photoresistor Documentation Support

### ISSUE THREAD

**Issue by adelgadoj3** [oss-slu/Pi4Micronaut#224]
Documentation requirements:

- [x] link to the documentation
- [x] Overview 
- [x] Components
- [x] Assembly Instructions
- [x] Circuit Diagram
- [x] Functionality
- [x] Testing
- [x] Troubleshooting
- [x] YAML
- [x] Constructor and Methods
- [x] Example Controller

**Comment by ruthvikm** [comment]
This issue was resolved
