### ISSUE TITLE
Micro Switch Implementation

### ISSUE THREAD

**Issue by SwindleA** [oss-slu/Pi4Micronaut#233]
sunfounder example: https://docs.sunfounder.com/projects/raphael-kit/en/latest/python/2.1.2_micro_switch_python.html

- [x] Implement Helper
- [x] Implement Controller
- [x] Add to application.yml
- [x] Write Javadoc comments

**Comment by joefol** [comment]
Closed by PR #234. Need to create an issue for micro switch documentation.
