### ISSUE TITLE
Thermistor Support

### ISSUE THREAD

**Issue by GreihMurray** [oss-slu/Pi4Micronaut#39]
Given:
A thermistor sensor is connected to the Raspberry Pi.

When:
The temperature is measured.

Then:
Real-time temperature data is provided in Celsius or Fahrenheit.

**Component Functionality:**
This component will enable the Pi4Micronaut project to measure temperature through a thermistor, providing real-time temperature data for monitoring and automation tasks.

**Developer Notes:**

1. Draw the circuit setup for hardware connections: Show how the thermistor connects to the Raspberry Pi via an analog-to-digital converter (ADC).
2.  Develop functionality to read temperature: Create a ThermistorHelper.java class to read raw data from the thermistor and convert it to temperature in Celsius or Fahrenheit.
3.  Implement conversion algorithms: Convert the resistance reading from the thermistor into a meaningful temperature value using the appropriate formula.
4. Configure GPIO pins and ADC appropriately: Ensure compatibility with various thermistors and ADCs.
5. Create an example controller in componets folder to clearly demonstate the working of helper class.
6.  Create a YAML configuration file for sensor settings: Add fields like name, address, pull_Down, debounce, provider.
7. Provide code comments for each function for future documentation.

Acceptance Criteria:

- [ ] Functionality to read the temperature data: The thermistor should provide accurate temperature readings.
- [ ] Component defined in YAML file with:
    - [ ] name
    - [ ] address
    - [ ] pull
    - [ ] debounce
    - [ ] provider
- [ ] Schematic diagram accurately depicts the wiring for the thermistor and ADC.
- [ ] Controller Implementation in components folder
- [ ] Code comments provided for each functionality for documentation purposes.

**Comment by yrlmanoharreddy** [comment]
Below are the comments given by @GreihMurray 

Need to add support for a thermistor, possibly a DigitalInput device but uncertain.
