### ISSUE TITLE
4 Digit 7 Segment Display

### ISSUE THREAD

**Issue by GreihMurray** [oss-slu/Pi4Micronaut#44]
Given:
A four-digit seven-segment display is connected to the Raspberry Pi.

When:
Data is sent to the display.

Then:
The display shows the appropriate four-digit numeric or character values based on the input.

**Component Functionality:**
This component will allow the Pi4Micronaut project to display multi-digit numbers (e.g., clock, counters) on a four-digit seven-segment display for advanced monitoring and control purposes.

**Developer Notes:**

1. Draw the circuit setup for hardware connections: Show how the four-digit display connects to GPIO pins, including common anode/cathode configurations.
2. Develop functionality to control the display: Create a FourDigitSevenSegmentDisplayHelper.java class to manage individual digits and segments.
3. Implement methods to display multi-digit numbers: Support numbers (0000-9999) and basic character representation.
4. Handle multiplexing: Implement the timing logic to control all four digits using multiplexing.
5. Configure GPIO pins appropriately: Ensure compatibility with common four-digit seven-segment displays.
6. Create an example controller in componets folder to clearly demonstate the working of helper class.
7. Create a YAML configuration file for display settings: Add fields like name, address, commonType, provider.
8. Provide code comments for each function for future documentation.

**Acceptance Criteria:**

- [ ] Functionality to control the four-digit display: Should support multi-digit numbers and characters.
- [ ] Component defined in YAML file with:
    - [ ]  name
    - [ ]  bus
    - [ ]  device
- [ ]  Controller Implementation in components folder
- [ ] Schematic diagram accurately depicts the wiring for the four-digit display.
- [ ] Code comments provided for each functionality for documentation purposes
- [ ] **Complete the hardware testing for this component**

**Comment by yrlmanoharreddy** [comment]
@GreihMurray  comments

May be an SPI component, may be I2C, may be DigitalOutput, answer is unclear. Unfortunately CrowPi does not have support for this component so code will have to be handled manually
