### ISSUE TITLE
Fan Support

### ISSUE THREAD

**Issue by GreihMurray** [oss-slu/Pi4Micronaut#45]
Add support for controlling a fan using the Pi4J library. This involves creating a class that handles fan initialization, speed control, and state management.
**Tasks:**
    

1.  Include a circuit diagram and breadboard layout.
2. Integrate GPIO pin configuration for fan control. Like yaml configurations
3. Create FanHelper.java class.
4. Implement methods for:
Starting the fan
Stopping the fan
Setting the speed of the fan
5. Provide functioning code to integrate the component with Micronaut.

**Acceptance Criteria:** 

  1. FanController.java class with methods: start(), stop(), and setSpeed(int speed).
  2. GPIO pin configuration.
  3. Component operates correctly on hardware.

**Comment by yrlmanoharreddy** [comment]
Add support for controlling a fan using the Pi4J library. This involves creating a class that handles fan initialization, speed control, and state management.
**Tasks:**
    

    1.  Include a circuit diagram and breadboard layout.
    2. Integrate GPIO pin configuration for fan control.
    3. Create FanController.java class.
    4. Implement methods for:
         Starting the fan
         Stopping the fan
         Setting the speed of the fan
    5. Provide functioning code to integrate the component with Micronaut.

**Acceptance Criteria:** 

      1.     FanController.java class with methods: start(), stop(), and setSpeed(int speed).
      2.     GPIO pin configuration.
      5.     Component operates correctly on hardware.

**Comment by yrlmanoharreddy** [comment]
Greih Murray old comments about the issue

Includes the need for a circuit, breadboard diagram, and functioning code to integrate the component with Micronaut

Will likely be a PWM device but not certain.
