### ISSUE TITLE
Hardware Component Guide

### ISSUE THREAD

**Issue by traison-diedrich** [oss-slu/Pi4Micronaut#58]
Create a detailed guide on how a developer would go about creating support for one of our already-supported hardware components. This should walk a potential developer through the exact steps they would need to take to mark a components support as completed. This should include 1. Circuit Building 2. Python testing 3. Java Implementation 4. Micronaut Integration 5. Controller Implementation 6. Documentation. This guide should be included in the "Contributing to the Library" section of our documentation. This would be a great first issue for any new developers joining the project to get quickly up to speed with the development process.

**Comment by SwindleA** [comment]
Completed by issue #71
