### ISSUE TITLE
Remove credentials from source repo

### ISSUE THREAD

**Issue by osscontributor** [oss-slu/Pi4Micronaut#61]
At https://github.com/oss-slu/Pi4Micronaut/blob/a1feb7122dd89032fd1c12c24d9e512d73efc018/micronautpi4j-utils/gradle.properties are presently sonatype credentials.  

The build should probably be reconfigured so those credentials are not kept in source code.  For GitHub actions, configuring those as GitHub Secrets ([docs.github.com/en/actions/security-guides/using-secrets-in-github-actions](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)) might be the best option.

**Comment by ruthvikm** [comment]
This issue was resolved
