### ISSUE TITLE
Documentation for RGB LED Setup

### ISSUE THREAD

**Issue by ruthvikm** [oss-slu/Pi4Micronaut#74]
Document the circuit process of RGB LED setup like what components are used (with details), pin configuration (clearly label the pins on the RGB LED and other components). Use pictures and circuit diagrams.

**Comment by kate-holdener** [comment]
There is a starting point for this documentation: https://oss-slu.github.io/Pi4Micronaut/#_rgb_led
However, it would be nice to have a hardware diagram demonstrating the hardware setup. Also, I see mentions of "unresolved directive" on that page (see attached screenshot), which are probably documentation bugs.
<img width="1195" alt="Screen Shot 2023-10-05 at 7 38 39 AM" src="https://github.com/oss-slu/Pi4Micronaut/assets/42073871/626f12ed-4584-446d-902f-fc0a8f12d66f">

**Comment by ruthvikm** [comment]
@joefol - Here I'm attaching the Circuit Diagram.
Following link we will be useful for your documentation
Link - https://docs.sunfounder.com/projects/raphael-kit/en/latest/c/1.1.2_rgb_led_c.html#c

**Comment by joefol** [comment]
Closing this issue, see PR #79 for code changes. Issue created to address the "unresolved directive" bug.
