### ISSUE TITLE
Fix "unresolved directive" Documentation Bug

### ISSUE THREAD

**Issue by SwindleA** [oss-slu/Pi4Micronaut#75]
Several instances of referencing Java code and it not showing up properly in the documentation. 

![image](https://github.com/oss-slu/Pi4Micronaut/assets/60612512/b292eb92-019b-426a-8424-e8fd949f2fdb)

**Comment by SwindleA** [comment]
previous fix did not work. attempted to fix by referencing the code through externally getting from the github.

**Comment by SwindleA** [comment]
not completed

**Comment by ruthvikm** [comment]
This issue was resolved
